Add debounce to query update
DagsHub/design-system pull request #88
Opened 2024-01-25 10:20 UTC by TalMalka123

2024-01-25 13:34 UTC, simonlsk requested changes
Do another round of simplification if possible.

2024-01-25 13:34 UTC, simonlsk commented on src/components/dagshub/data-engine/queryBuilder/QueryBuilderContext.tsx
> +    setIsCompoundModeForced(!isCompoundModeForced);
```suggestion
    setIsSimpleMode((isSimple) => { 
    if (isSimple) {
    return false
    } else {
    return isDisplayableInSimpleMode
    })
```

2024-01-28 09:21 UTC, simonlsk requested changes
LGTM in general. 
I was thinking maybe to delegate the debounce to the text input component, WDYT?

2024-01-28 09:21 UTC, simonlsk commented on src/components/dagshub/data-engine/queryBuilder/QueryBuilderContext.tsx
> +  const debouncedOnChange = useCallback(
Wouldn't be nicer to just debounce `onChange` in the `ConditionTextField` ? That way only the text keyboard inputs are debounced.

2024-01-29 11:34 UTC, TalMalka123 commented on src/components/dagshub/data-engine/queryBuilder/QueryBuilderContext.tsx
> +    setIsSimpleMode((isSimpleMode) => {
@simonlsk told me that when I want to change the state, I should not use the variable from the state definition, but use the prev from the func, so there won't be race conditioning @elad-n

2024-01-29 11:46 UTC, simonlsk commented on src/components/dagshub/data-engine/queryBuilder/QueryBuilderContext.tsx
> +    setIsSimpleMode((isSimpleMode) => {
https://stackoverflow.com/a/61313526

2024-01-29 11:53 UTC, TalMalka123 commented on src/components/dagshub/data-engine/queryBuilder/QueryBuilderContext.tsx
> +  const [isSimpleMode, setIsSimpleMode] = useState<boolean>(isDisplayableInSimpleMode);
I'm not sure I understand. My use-state hooks are at the top. Before them there are just functions that the state uses, so they must be defined before the state itself, for them to be recognized. 
According to the article, it doesn't seem to break any rule cause there is no prior return statement within the component itself (unless I miss something), and the hooks are not within any function/condition.

@elad-n Let me know if I miss something, and what I need to do

2024-01-29 12:08 UTC, TalMalka123 commented on src/components/dagshub/data-engine/queryBuilder/QueryBuilderContext.tsx
> +    setIsSimpleMode((isSimpleMode) => {
I guess its the same comment like before: https://github.com/DagsHub/design-system/pull/88#discussion_r1469474437

2024-01-29 14:20 UTC, simonlsk approved these changes

2024-01-29 14:20 UTC, simonlsk commented on package.json
> +  "version": "0.1.77",
bump

2024-01-29 14:38 UTC, merged